In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
sent = ['th glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good']

In [4]:
sent

['th glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
# define the vocaublary size

voc_size = 10000

In [6]:
#One hot Representation

one_hot_repr=[one_hot(words, voc_size)for words in sent]
one_hot_repr

[[6589, 6888, 7971, 7573],
 [2536, 6888, 7971, 4210],
 [2536, 3186, 7971, 8595],
 [2296, 5511, 4340, 9627, 4129],
 [2296, 5511, 4340, 9627, 4773],
 [1406, 2536, 5769, 7971, 5710],
 [1351, 2405, 8579, 9627]]

In [7]:
## Word embedding represeantiaon

In [8]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np


In [10]:
sent_length = 8
embedding_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedding_docs)

[[   0    0    0    0 6589 6888 7971 7573]
 [   0    0    0    0 2536 6888 7971 4210]
 [   0    0    0    0 2536 3186 7971 8595]
 [   0    0    0 2296 5511 4340 9627 4129]
 [   0    0    0 2296 5511 4340 9627 4773]
 [   0    0    0 1406 2536 5769 7971 5710]
 [   0    0    0    0 1351 2405 8579 9627]]


In [11]:
## feature representation

dim = 10


In [12]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam', 'mse')

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
model.predict(embedding_docs)

1/1 [==============================] - 0s 175ms/step


array([[[-0.02292688, -0.00102898,  0.00842119, -0.01332179,
         -0.01860904,  0.01048303,  0.03133813,  0.04871185,
         -0.0468028 ,  0.03530524],
        [-0.02292688, -0.00102898,  0.00842119, -0.01332179,
         -0.01860904,  0.01048303,  0.03133813,  0.04871185,
         -0.0468028 ,  0.03530524],
        [-0.02292688, -0.00102898,  0.00842119, -0.01332179,
         -0.01860904,  0.01048303,  0.03133813,  0.04871185,
         -0.0468028 ,  0.03530524],
        [-0.02292688, -0.00102898,  0.00842119, -0.01332179,
         -0.01860904,  0.01048303,  0.03133813,  0.04871185,
         -0.0468028 ,  0.03530524],
        [-0.03776361,  0.00303459,  0.00775552, -0.01311588,
         -0.03098042, -0.01155533, -0.00453621,  0.04013263,
          0.02039916,  0.01025737],
        [-0.0186693 ,  0.04114541, -0.00819697, -0.01361016,
         -0.03590513, -0.03144963,  0.01965162,  0.01876125,
          0.02555425,  0.03525552],
        [ 0.02474042, -0.01688683, -0.04310663, -0.0

In [16]:
#chckc first sentence

embedding_docs[0]

array([   0,    0,    0,    0, 6589, 6888, 7971, 7573])

In [17]:
model.predict(embedding_docs[0])

1/1 [==============================] - 0s 36ms/step


array([[-0.02292688, -0.00102898,  0.00842119, -0.01332179, -0.01860904,
         0.01048303,  0.03133813,  0.04871185, -0.0468028 ,  0.03530524],
       [-0.02292688, -0.00102898,  0.00842119, -0.01332179, -0.01860904,
         0.01048303,  0.03133813,  0.04871185, -0.0468028 ,  0.03530524],
       [-0.02292688, -0.00102898,  0.00842119, -0.01332179, -0.01860904,
         0.01048303,  0.03133813,  0.04871185, -0.0468028 ,  0.03530524],
       [-0.02292688, -0.00102898,  0.00842119, -0.01332179, -0.01860904,
         0.01048303,  0.03133813,  0.04871185, -0.0468028 ,  0.03530524],
       [-0.03776361,  0.00303459,  0.00775552, -0.01311588, -0.03098042,
        -0.01155533, -0.00453621,  0.04013263,  0.02039916,  0.01025737],
       [-0.0186693 ,  0.04114541, -0.00819697, -0.01361016, -0.03590513,
        -0.03144963,  0.01965162,  0.01876125,  0.02555425,  0.03525552],
       [ 0.02474042, -0.01688683, -0.04310663, -0.04976571, -0.03656035,
        -0.04355909,  0.00393884,  0.0056561 